# Generated by Django 5.0.6 on 2024-09-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
